### ISSUE TITLE
ElectronConvFitProb not filled

### ISSUE THREAD

**Issue by sethcooper** [CMSLQ/RootTupleMakerV2#2]
This branch is not currently filled in the ntuple.
I don't think the values to compute it are easily accessible in the MiniAOD, and it is not used in the offline electron ID.
I am not sure if it's used for something else.
Could be implemented if really needed.
Otherwise, we should remove it.

**Comment by edmundaberry** [comment]
It can be removed.  We never used it in the past, and it doesn't look like it will be useful in the future.

**Comment by sethcooper** [comment]
Thanks, Edmund! Removed.
