### ISSUE TITLE
Add HEEP v7.0 track isolation

### ISSUE THREAD

**Issue by DavidMorse** [CMSLQ/RootTupleMakerV2#28]
https://twiki.cern.ch/twiki/bin/view/CMS/HEEPElectronIdentificationRun2#Selection_Cuts_HEEP_V7_0_recomme

**Comment by sethcooper** [comment]
Done and tested: https://github.com/CMSLQ/RootTupleMakerV2/commit/124da3c198416508df6e8a8b85e2303e511876aa
