### ISSUE TITLE
Update PDF variations in MadGraph / amc@NLO

### ISSUE THREAD

**Issue by DavidMorse** [CMSLQ/RootTupleMakerV2#31]
Make sure to include PDF4LHC

**Comment by sethcooper** [comment]
It looks like we are getting values in the ntuple branches for the Moriond17 signal sample I tried.  I think they look reasonable—they are all peaking at 1 with some spread.

So I guess that this works in pythia.
The issue is then to make sure it works and/or extend it to work in MadGraph and amc@NLO as well?

**Comment by sethcooper** [comment]
Results of further testing with various generator schemes that we use:
- madgraphMLM: external PDF weight producer appears to work
- amc@NLO: external PDF weight producer does not work, no PDF weights look OK
- powhegv2/madspin/pythia8: external PDF weight producer does not work, but NNPDF weights available
- powheg/pythia8: doesn't look good either

I believe that for those that do not work with the external weight producer, one can extract the PDF weights from the LHERunInfoProduct, as per: https://twiki.cern.ch/twiki/bin/viewauth/CMS/LHEReaderCMSSW#How_to_use_weights

**Comment by DavidMorse** [comment]
Status update: tl;dr NNPDF weights (101 variations per event) are available for all samples - but there are some caveats.

Assumption made is that we will only use NNPDF weights.

- madgraphMLM: external PDF weight producer works, CT, MMTH, NNPDF all good

- amc@NLO: external PDF weight producer only has NNPDF weights. They are stored in PDFAmcNLOWeights instead of PDFNNPDFWeights. Annoying, but necessary, as amc@NLO weights (+-200000) are applied in standard PDFNNPDFWeights setup. There are no CT or MMTH weights.

- powheg:  external PDF weight producer only has NNPDF weights. Available as PDFNNPDFWeights. There are no CT or MMTH weights.

- pythia8 (signal): Weights available from all PDF sets from PDFWeightProducer. However, ~2/3 of events have no weights at all(!!). Following up with generator hypernews. Currently setting all PDF variations to 1 if they are 0...

**Comment by DavidMorse** [comment]
PDFNNPDFWeights should work for all generators since https://github.com/CMSLQ/RootTupleMakerV2/commit/01f0474503cb79cf8faa5728f6712ec91ef736e1
